//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.8.5.
// DekaMoji_res.rc

#define IDB_WAIT                            100

#define IDD_MAINDLG                         100
#define IDD_NAMESETTINGS                    101
#define IDD_CHOOSEDELETESETTINGS            102

#define IDR_SETTINGS_MENU                   100

#define IDS_APPNAME                         100
#define IDS_INVALIDSTRING                   101
#define IDS_TEXTTOOLONG                     102
#define IDS_PORTRAIT                        103
#define IDS_LANDSCAPE                       104
#define IDS_A3                              105
#define IDS_A4                              106
#define IDS_A5                              107
#define IDS_B4                              108
#define IDS_B5                              109
#define IDS_LOGO                            110
#define IDS_GENERATEFAILED                  111
#define IDS_SUCCEEDED                       112
#define IDS_GENERATE                        113
#define IDS_PROCESSINGNOW                   114
#define IDS_FONT_01                         115
#define IDS_SAMPLETEXT                      116
#define IDS_FIELD_TEXT                      117
#define IDS_REASON_EMPTY_TEXT               118
#define IDS_OUTPUT_NAME                     119
#define IDS_YES                             120
#define IDS_NO                              121
#define IDS_FIELD_TEXT_COLOR                125
#define IDS_REASON_VALID_COLOR              126
#define IDS_FIELD_FONT_NAME                 127
#define IDS_SIZE_LEGAL                      128
#define IDS_SIZE_LETTER                     129
#define IDS_REGFILTER                       135
#define IDS_OPEN_PARENS                     136
#define IDS_CLOSE_PARENS                    137
#define IDS_COMMA_PERIOD                    138
#define IDS_HYPHEN_DASH                     139
#define IDS_SMALL_KANA                      140
#define IDS_REASON_INVALID_INTEGER          141
#define IDS_ASPECT_100                      142
#define IDS_ASPECT_150                      143
#define IDS_ASPECT_200                      144
#define IDS_ASPECT_250                      145
#define IDS_ASPECT_300                      146
#define IDS_ASPECT_400                      147
#define IDS_ASPECT_NO_LIMIT                 148

#define ID_SAVESETTINGSAS                   1000
#define ID_RESETSETTINGS                    1001
#define ID_INITAPP                          1002
#define ID_CHOOSESETTINGSTODELETE           1003
#define ID_SAVEALLTOREGFILE                 1004
#define ID_SETTINGS_000                     1005
#define ID_OVERWRITE_SETTINGS_000           2005

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    101
        #define _APS_NEXT_COMMAND_VALUE     2006
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
