//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.8.4.
// DMPDF_res.rc

#define IDS_APPNAME                         100
#define IDS_INVALIDSTRING                   101
#define IDS_TEXTTOOLONG                     102
#define IDS_PORTRAIT                        103
#define IDS_LANDSCAPE                       104
#define IDS_A3                              105
#define IDS_A4                              106
#define IDS_A5                              107
#define IDS_B4                              108
#define IDS_B5                              109
#define IDS_LOGO                            110
#define IDS_COPYFILEFAILED                  111
#define IDS_SUCCEEDED                       112
#define IDS_GENERATE                        113
#define IDS_PROCESSINGNOW                   114
#define IDS_FONT_01                         115
#define IDS_SAMPLETEXT                      116
#define IDS_FIELD_TEXT                      117
#define IDS_REASON_EMPTY_TEXT               118
#define IDS_OUTPUT_NAME                     119
#define IDS_YES                             120
#define IDS_NO                              121
#define IDS_METHOD_01                       122
#define IDS_METHOD_02                       123
#define IDS_METHOD_03                       124
#define IDS_FIELD_TEXT_COLOR                125
#define IDS_REASON_VALID_COLOR              126
#define IDS_FIELD_FONT_NAME                 127

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
